# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hrd < Formula
  desc "Multi-repo manager for git and jj with parallel execution and live status"
  homepage "https://github.com/hugoh/hrd"
  version "1.2.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hugoh/hrd/releases/download/v1.2.5/hrd_1.2.5_darwin_amd64.tar.gz"
      sha256 "fa64675535186874c40d46853af0b1b27020a8619dd6fa5417312154ccea5efb"

      define_method(:install) do
        bin.install "hrd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hugoh/hrd/releases/download/v1.2.5/hrd_1.2.5_darwin_arm64.tar.gz"
      sha256 "e68a537f2175420a855a64ee2c14531ab71e1e53e6940d102d022c02471c6dec"

      define_method(:install) do
        bin.install "hrd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hugoh/hrd/releases/download/v1.2.5/hrd_1.2.5_linux_amd64.tar.gz"
      sha256 "58790ae6956b7a4d89ac08910b947b0123dda6e4a00c73f3e57df2c7b888bbdf"
      define_method(:install) do
        bin.install "hrd"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hugoh/hrd/releases/download/v1.2.5/hrd_1.2.5_linux_armv6.tar.gz"
      sha256 "c55af1bb39820f9e7964aae0772ed887702266734b4daaee7e0eb38e3ba5c6db"
      define_method(:install) do
        bin.install "hrd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hugoh/hrd/releases/download/v1.2.5/hrd_1.2.5_linux_arm64.tar.gz"
      sha256 "65335b7526bc3ea5a372158b326844c80e587edef02627726b993b12c1c75081"
      define_method(:install) do
        bin.install "hrd"
      end
    end
  end
end
