# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JjTrim < Formula
  desc "Clean up merged bookmarks and abandoned anonymous commits in jj repositories"
  homepage "https://github.com/hugoh/jj-trim"
  version "0.3.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hugoh/jj-trim/releases/download/v0.3.2/jj-trim_0.3.2_darwin_amd64.tar.gz"
      sha256 "24d2c797e1addb940950953728945b66f98ce1c3a5b595615702fe0babb94924"

      define_method(:install) do
        bin.install "jj-trim"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hugoh/jj-trim/releases/download/v0.3.2/jj-trim_0.3.2_darwin_arm64.tar.gz"
      sha256 "0db641fc1b220567fd5e4ddf2c8368f5644462597e74bf385ed80e5b97a93b6f"

      define_method(:install) do
        bin.install "jj-trim"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hugoh/jj-trim/releases/download/v0.3.2/jj-trim_0.3.2_linux_amd64.tar.gz"
      sha256 "dca5c40d12b50e05c31e8acf19c4ed681990cc279318a71abf6a8465da43a178"
      define_method(:install) do
        bin.install "jj-trim"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hugoh/jj-trim/releases/download/v0.3.2/jj-trim_0.3.2_linux_armv6.tar.gz"
      sha256 "adf5918379abf8a42cd440de091cee9181098c1f7ba90b83a62ec9b7c5978b20"
      define_method(:install) do
        bin.install "jj-trim"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hugoh/jj-trim/releases/download/v0.3.2/jj-trim_0.3.2_linux_arm64.tar.gz"
      sha256 "803a837b058f2d9ccadbc0c0571bdf5bd11b03ca26cbbe5087e7b2424e2c5e28"
      define_method(:install) do
        bin.install "jj-trim"
      end
    end
  end
end
