# This file was generated by GoReleaser. DO NOT EDIT.
cask "hrd" do
  version "0.13.1"

  on_macos do
    on_intel do
      sha256 "7c861eedafb28dec1734ba08ca93ec0635467a9fd06dccc0c0a2d471cf1b59f6"
      url "https://github.com/hugoh/hrd/releases/download/v#{version}/hrd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0cb05afd4d2c7733e22f2b87ba83e04647ee62843527667957f767b50136b023"
      url "https://github.com/hugoh/hrd/releases/download/v#{version}/hrd_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "392bbfbfa65a158061ac6393de67fd10f9d4bd3a3beb0a314817a23e42ea8de1"
      url "https://github.com/hugoh/hrd/releases/download/v#{version}/hrd_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a8996aef43282a38be4f3ed10c64afddce75fdfde25b49887b8313695e8fc646"
      url "https://github.com/hugoh/hrd/releases/download/v#{version}/hrd_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hrd"
  desc "Multi-repo manager for git and jj with parallel execution and live status"
  homepage "https://github.com/hugoh/hrd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hrd"

  # No zap stanza required

end
