# This file was generated by GoReleaser. DO NOT EDIT.
cask "hrd" do
  version "0.15.0"

  on_macos do
    on_intel do
      sha256 "2766902a9f7b2497c53a8a7c6bdd5f365a80c080ce72bfa62f91585023872458"
      url "https://github.com/hugoh/hrd/releases/download/v#{version}/hrd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8da75e4b5d4530bcac3971ac91147089a39f85e83fed51a6201be59fd1ca2496"
      url "https://github.com/hugoh/hrd/releases/download/v#{version}/hrd_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "96087c9c1b1f59008158b42c9a21a5ebaeec574fc3adf5b810640f5afc7c4929"
      url "https://github.com/hugoh/hrd/releases/download/v#{version}/hrd_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9ecf5dfcc5e5053df911372fefe3ab157c5d4955b93d8c093f6af736543d1808"
      url "https://github.com/hugoh/hrd/releases/download/v#{version}/hrd_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hrd"
  desc "Multi-repo manager for git and jj with parallel execution and live status"
  homepage "https://github.com/hugoh/hrd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hrd"

  # No zap stanza required

end
