# This file was generated by GoReleaser. DO NOT EDIT.
cask "hrd" do
  version "0.15.3"

  on_macos do
    on_intel do
      sha256 "a0f1a94b8d5cda375605962125bbc78ee9f0c30a8bceecb0a2ecd9f72348e98a"
      url "https://github.com/hugoh/hrd/releases/download/v#{version}/hrd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7d7495a95553aee9bb9b7663ea624f53b8cbb2928150fc0bc8d624de9a180e21"
      url "https://github.com/hugoh/hrd/releases/download/v#{version}/hrd_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0f32b53cdf1ef6bb998bf56207b2f540bc326adc2672997cfda57699afef4515"
      url "https://github.com/hugoh/hrd/releases/download/v#{version}/hrd_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "98d61db48a58fcd8cbd537f330e123d6a744c3da06effe603ab473904dcf1613"
      url "https://github.com/hugoh/hrd/releases/download/v#{version}/hrd_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hrd"
  desc "Multi-repo manager for git and jj with parallel execution and live status"
  homepage "https://github.com/hugoh/hrd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hrd"

  # No zap stanza required

end
