# This file was generated by GoReleaser. DO NOT EDIT.
cask "jj-trim" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "0d70b4a7768c3ccb543535c684a315fadf6d18e64da9e617729a6f294be59760"
      url "https://github.com/hugoh/jj-trim/releases/download/v#{version}/jj-trim_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "93bd5ab2b03fefb279fd217d8c6d785311621be0af76b838f99246cf65ef8433"
      url "https://github.com/hugoh/jj-trim/releases/download/v#{version}/jj-trim_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f00c55239ad64555534a3832c9050bf29606a73d7b8a3e485e22faa6c1ad0c01"
      url "https://github.com/hugoh/jj-trim/releases/download/v#{version}/jj-trim_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3af79c0bcffbb2db5390f524bff2765899d08f321af39d544c91de34dacd889f"
      url "https://github.com/hugoh/jj-trim/releases/download/v#{version}/jj-trim_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jj-trim"
  desc "Clean up merged bookmarks and abandoned anonymous commits in jj repositories"
  homepage "https://github.com/hugoh/jj-trim"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jj-trim"

  # No zap stanza required

end
