# This file was generated by GoReleaser. DO NOT EDIT.
cask "jj-trim" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "8d90136761407d0b1265774759ff8fa836a329ea4cc9b73bbe80b0adcd4da0c0"
      url "https://github.com/hugoh/jj-trim/releases/download/v#{version}/jj-trim_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "13a695177a2fc26b782da837760cd6724217fece22874663c422d870aea54eed"
      url "https://github.com/hugoh/jj-trim/releases/download/v#{version}/jj-trim_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c69b78cc567c58156a57c02bf8f75617aecc088e963102d5041efada143077cf"
      url "https://github.com/hugoh/jj-trim/releases/download/v#{version}/jj-trim_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ba114f5ed3e2674f86df11ff6b0a76240f2119240b66e71123ea4e5116192db8"
      url "https://github.com/hugoh/jj-trim/releases/download/v#{version}/jj-trim_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jj-trim"
  desc "Clean up merged bookmarks and abandoned anonymous commits in jj repositories"
  homepage "https://github.com/hugoh/jj-trim"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jj-trim"

  # No zap stanza required

end
