# This file was generated by GoReleaser. DO NOT EDIT.
cask "jj-trim" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "206865807ebb551ec59b2e904b0496746ea6f38bfcce11188445e5e6a9fc26df"
      url "https://github.com/hugoh/jj-trim/releases/download/v#{version}/jj-trim_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a5a17bf051c9586086dcb9a3db3fe12942450d18afdcbb475320e19400bb7715"
      url "https://github.com/hugoh/jj-trim/releases/download/v#{version}/jj-trim_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "04d07d0050717b055931e29bc5e3701418eb3e576d6e1cf9756d386f7657aac4"
      url "https://github.com/hugoh/jj-trim/releases/download/v#{version}/jj-trim_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8a4cf0aa574a7359ab4d801637e4ecd979bf2e427cb8d4e534e6026a24af7891"
      url "https://github.com/hugoh/jj-trim/releases/download/v#{version}/jj-trim_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jj-trim"
  desc "Clean up merged bookmarks and abandoned anonymous commits in jj repositories"
  homepage "https://github.com/hugoh/jj-trim"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jj-trim"

  # No zap stanza required

end
