# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hrd < Formula
  desc "Multi-repo manager for git and jj with parallel execution and live status"
  homepage "https://github.com/hugoh/hrd"
  version "1.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hugoh/hrd/releases/download/v1.5.0/hrd_1.5.0_darwin_amd64.tar.gz"
      sha256 "6a8de81f9734c21c4df215167c465f99a62aa00cd3ee55469c7e2ca8db7ad17f"

      define_method(:install) do
        bin.install "hrd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hugoh/hrd/releases/download/v1.5.0/hrd_1.5.0_darwin_arm64.tar.gz"
      sha256 "df65503a4119fc15a986bcc0bd9c8b88a8f803fa613cb900172488f0cc53340e"

      define_method(:install) do
        bin.install "hrd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hugoh/hrd/releases/download/v1.5.0/hrd_1.5.0_linux_amd64.tar.gz"
      sha256 "e2f8a7173c5509077f43c2d661b175f85be60dc726601db7001dda4636746ad5"
      define_method(:install) do
        bin.install "hrd"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hugoh/hrd/releases/download/v1.5.0/hrd_1.5.0_linux_armv6.tar.gz"
      sha256 "d37c649c15ee51f959183f9d65ccdb686e83e0884dee00f26335805ba81adc4e"
      define_method(:install) do
        bin.install "hrd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hugoh/hrd/releases/download/v1.5.0/hrd_1.5.0_linux_arm64.tar.gz"
      sha256 "9c89c078c9843d6f1a524df456c94e7b222f3e53375010609a5bec9c56179de6"
      define_method(:install) do
        bin.install "hrd"
      end
    end
  end
end
