# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JjTrim < Formula
  desc "Clean up merged bookmarks and abandoned anonymous commits in jj repositories"
  homepage "https://github.com/hugoh/jj-trim"
  version "0.3.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hugoh/jj-trim/releases/download/v0.3.4/jj-trim_0.3.4_darwin_amd64.tar.gz"
      sha256 "3256250802ab7ddbf842f8ac031167be4e6157798913924e26b794e10f03ce32"

      define_method(:install) do
        bin.install "jj-trim"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hugoh/jj-trim/releases/download/v0.3.4/jj-trim_0.3.4_darwin_arm64.tar.gz"
      sha256 "f7d4da9d245b11537bbb7881b29ed0acd3cbdde8eb58ab0c1dbe2cc72f19dd7e"

      define_method(:install) do
        bin.install "jj-trim"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hugoh/jj-trim/releases/download/v0.3.4/jj-trim_0.3.4_linux_amd64.tar.gz"
      sha256 "4ba54354039faf2dfdd4c06ceead501756e0a5f8f01649fab5633d08b270e131"
      define_method(:install) do
        bin.install "jj-trim"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hugoh/jj-trim/releases/download/v0.3.4/jj-trim_0.3.4_linux_armv6.tar.gz"
      sha256 "88bfb5b7425197db9f343e9293e8871464957fcc0990ef2fa5ce23fe2b297e0f"
      define_method(:install) do
        bin.install "jj-trim"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hugoh/jj-trim/releases/download/v0.3.4/jj-trim_0.3.4_linux_arm64.tar.gz"
      sha256 "2ac993dba84d7563cfbf227a01195a1f916f9cc6d3059f2c83999ac17a239595"
      define_method(:install) do
        bin.install "jj-trim"
      end
    end
  end
end
