# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TmhiCli < Formula
  desc "CLI for managing T-Mobile Home Internet gateway and signal monitoring"
  homepage "https://github.com/hugoh/tmhi-cli"
  version "1.9.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hugoh/tmhi-cli/releases/download/v1.9.11/tmhi-cli_1.9.11_darwin_amd64.tar.gz"
      sha256 "2b193703afd2ed2970d6f430e0dddd26e88777ee5cdfb79c9725ab25e95df956"

      define_method(:install) do
        bin.install "tmhi-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hugoh/tmhi-cli/releases/download/v1.9.11/tmhi-cli_1.9.11_darwin_arm64.tar.gz"
      sha256 "4ddabb3ae6cc1178655301df99b9b6dacbcff55da61ff9aceb833417998645f3"

      define_method(:install) do
        bin.install "tmhi-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hugoh/tmhi-cli/releases/download/v1.9.11/tmhi-cli_1.9.11_linux_amd64.tar.gz"
      sha256 "350883fb332bcb4b9604ac122ec9da7680aa6a7dfa51553bd1ec32bf3c9ee000"
      define_method(:install) do
        bin.install "tmhi-cli"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hugoh/tmhi-cli/releases/download/v1.9.11/tmhi-cli_1.9.11_linux_armv6.tar.gz"
      sha256 "bf54bfa18769f853d374a4209ba8d762bc5370591d6571d5117192a1d7aca5ea"
      define_method(:install) do
        bin.install "tmhi-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hugoh/tmhi-cli/releases/download/v1.9.11/tmhi-cli_1.9.11_linux_arm64.tar.gz"
      sha256 "8623b22822b094a3d0289a022decc1241526e5e45e80c436195a0f422df8b298"
      define_method(:install) do
        bin.install "tmhi-cli"
      end
    end
  end
end
