# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TmhiCli < Formula
  desc "CLI for managing T-Mobile Home Internet gateway and signal monitoring"
  homepage "https://github.com/hugoh/tmhi-cli"
  version "1.9.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hugoh/tmhi-cli/releases/download/v1.9.9/tmhi-cli_1.9.9_darwin_amd64.tar.gz"
      sha256 "75296b36931e180131de2db64da7f95f2c2ff174ff10c614221f41549d647529"

      define_method(:install) do
        bin.install "tmhi-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hugoh/tmhi-cli/releases/download/v1.9.9/tmhi-cli_1.9.9_darwin_arm64.tar.gz"
      sha256 "ead522ed6cab0139ec2f1ee772dad4e839fc3ba94332bdc9776bd5f8f197771b"

      define_method(:install) do
        bin.install "tmhi-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hugoh/tmhi-cli/releases/download/v1.9.9/tmhi-cli_1.9.9_linux_amd64.tar.gz"
      sha256 "74eca9c9b886d37e0502e3ddcda14a6004880aca3e0c43ecbccbb61668d89d63"
      define_method(:install) do
        bin.install "tmhi-cli"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hugoh/tmhi-cli/releases/download/v1.9.9/tmhi-cli_1.9.9_linux_armv6.tar.gz"
      sha256 "fe3e8fbc0b3c1028012b79c3609c925f7a416225772f4fe05c78522c6c23d9f1"
      define_method(:install) do
        bin.install "tmhi-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hugoh/tmhi-cli/releases/download/v1.9.9/tmhi-cli_1.9.9_linux_arm64.tar.gz"
      sha256 "70b8e31b7900b785c13a81d31f799abf852db6965b3d3cca1ac8da28e332ce6e"
      define_method(:install) do
        bin.install "tmhi-cli"
      end
    end
  end
end
