---
name: Keep auto-merge PRs fresh

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - auto_merge_enabled
  workflow_dispatch:

concurrency:
  group: automerge-keep-fresh
  cancel-in-progress: false

permissions: {}

jobs:
  update-behind-prs:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Update stale auto-merge PRs
        uses: hugoh/gh-workflows/automerge-keep-fresh@b13f1839dfa9e6c2baf7bbcbbcee858e0f8d8175 # v1.40.0
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
