---
name: hk

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  hk:
    uses: hugoh/gh-workflows/.github/workflows/hk.yml@b13f1839dfa9e6c2baf7bbcbbcee858e0f8d8175 # v1.40.0
    permissions:
      contents: read
      packages: read
      statuses: write
    with:
      pre-hk: |
        BREW_PREFIX=/home/linuxbrew/.linuxbrew
        echo "$BREW_PREFIX/bin" >> "$GITHUB_PATH"
        echo "$BREW_PREFIX/sbin" >> "$GITHUB_PATH"
